const [MAIN_CHUNK_MAX, MAIN_CHUNK_MEDIUM, MAIN_CHUNK_MIN] = [12, 8, 5];
const [EXTRA_CHUNK_MAX, EXTRA_CHUNK_MEDIUM, EXTRA_CHUNK_MIN] = [3, 2, 1];

export {
    MAIN_CHUNK_MAX, MAIN_CHUNK_MEDIUM, MAIN_CHUNK_MIN,
    EXTRA_CHUNK_MAX, EXTRA_CHUNK_MEDIUM, EXTRA_CHUNK_MIN
}
